In [2]:
import pandas as pd
import numpy as np

In [55]:
ds= pd.read_csv("titanicsurvival.csv")
print(ds)

     Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [8]:
ds.shape

(891, 5)

In [10]:
ds.head(5)

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [83]:
mean_age= ds['Age'].mean()
ds['Age']=ds['Age'].fillna(mean_age)

In [27]:
ds.head(5)

   Pclass  Sex   Age     Fare  Survived
0       3    1  22.0   7.2500         0
1       1    0  38.0  71.2833         1
2       3    0  26.0   7.9250         1
3       1    0  35.0  53.1000         1
4       3    1  35.0   8.0500         0

In [57]:
ds.head(10)

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0
5       3    male   NaN   8.4583         0
6       1    male  54.0  51.8625         0
7       3    male   2.0  21.0750         0
8       3  female  27.0  11.1333         1
9       2  female  14.0  30.0708         1

In [59]:
# Drop rows where 'Sex' has missing values
ds.dropna(subset=['Sex'], inplace=True)
ds['Sex'] = ds['Sex'].map({'female': 0, 'male': 1}).astype(int)

In [61]:
ds.head(5)

   Pclass  Sex   Age     Fare  Survived
0       3    1  22.0   7.2500         0
1       1    0  38.0  71.2833         1
2       3    0  26.0   7.9250         1
3       1    0  35.0  53.1000         1
4       3    1  35.0   8.0500         0

In [67]:
x= ds.drop('Survived', axis='columns')
x

     Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [75]:
y= ds['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [77]:
y.head(5)

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [89]:
x.columns[x.isna().any()]

Index(['Age'], dtype='object')

In [93]:
x.Age= x.Age.fillna(x.Age.mean())

In [95]:
x.columns[x.isna().any()]

Index([], dtype='object')

In [101]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25, random_state= 0)

In [153]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [145]:
x.columns

Index(['Pclass', 'Sex', 'Age', 'Fare'], dtype='object')

In [147]:
pclass= int(input("Enter the Pclass no. : "))
sex= int(input("Enter the Gender (Female=0 & Male=1) : "))
try:
    if(sex not in [0,1]):
        raise ValueError("Invalid input! Please enter 0 for Female or 1 for Male.")
except ValueError as e:
    print(e)

age=  int(input("Enter the Age : "))
fare= int(input("Enter Fare : "))

new_person=[[pclass,sex,age,fare]]
result= model.predict(new_person)
print(result)

if(result==1):
    print("The Person might be servived ")
else:
    print("The Person might not be servived ")

Enter the Pclass no. :  1
Enter the Gender (Female=0 & Male=1) :  1
Enter the Age :  1
Enter Fare :  1

[1]
The Person might be servived

G:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [155]:
y_pred= model.predict(x_test)
print(np.column_stack((y_pred,y_test)))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]

In [151]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm= confusion_matrix(y_test,y_pred)
print(cm)
print("The accurecy of the model is: {0}".format(accuracy_score(y_test,y_pred)*100))

[[117  22]
 [ 24  60]]
The accurecy of the model is: 79.37219730941703